### ISSUE TITLE
Groovy custom validator

### ISSUE THREAD

**Issue by shnplr** [griffon-plugins/griffon-validation-plugin#1]
Hi,
I could not get the custom validation to work using example in guide

My sample class is:

```
package sample.validator
import org.codehaus.griffon.runtime.validation.AbstractValidateable
class PermissionValidator extends AbstractValidateable {
    static final CONSTRAINTS = {
        password(nullable: false, blank: false, size: 1..30)
        password2(validator{ v, obj -> obj.password == val ? '' : 'passwords.do.not.match' })
    }
    String password2 = "fred"
    String password = "xxx"
}


package sample.controller
class PermissionController {
    void validate() {
        def validator = application.injector.getInstance(PermissionValidator.class)
    }
}
```

Caused by: groovy.lang.MissingMethodException: No signature of method: sample.validator.PermissionValidator.validator() is applicable for argument types: (sample.validator.PermissionValidator$__clinit__closure1$_closure2) values: [sample.validator.PermissionValidator$__clinit__closure1$_closure2@568795a8]
Possible solutions: validate([Ljava.lang.String;), validate(java.util.List)
    at sample.validator.PermissionValidator$__clinit__closure1.doCall(PermissionValidator.groovy:20)
    at sample.validator.PermissionValidator$__clinit__closure1.doCall(PermissionValidator.groovy)
    ... 21 more

In my case line 20 is the line starting with password2(validator {...})

I noticed the guide refers to validate() method but this method also doesn't seem to exist though I'm not sure what this has to do with the validator closure.

**Comment by aalmiray** [comment]
I see the problem now. The guide mistakenly shows the Groovy code to be

```
 password2(validator{ v, obj -> obj.password == val ? '' : 'passwords.do.not.match' })
```

but it should be

```
password2(validator: { v, obj -> obj.password == val ? '' : 'passwords.do.not.match' })
```

notice the additional semi-colons.

**Comment by shnplr** [comment]
Hi Andres,
I had tried with the colon + changing 'val' to 'v'. It produces a different error:

```
[2016-04-12 19:18:23,373] [griffon-pool-1-thread-2] ERROR griffon.plugins.validation.constraints.ConstrainedProperty - Exception thrown applying constraint [validator] to class [class au.edu.nsw.det.esbtoolsfx.validate.PermissionValidator] for value [au.edu.nsw.det.esbtoolsfx.validate.PermissionValidator$__clinit__closure1$_closure2@644d9b2d]: Parameter for constraint [validator] of property [password2] of class [class au.edu.nsw.det.esbtoolsfx.validate.PermissionValidator] must be one of [griffon.plugins.validation.constraints.PropertyValidator,griffon.plugins.validation.constraints.ObjectValidator]
java.lang.IllegalStateException: Parameter for constraint [validator] of property [password2] of class [class au.edu.nsw.det.esbtoolsfx.validate.PermissionValidator] must be one of [griffon.plugins.validation.constraints.PropertyValidator,griffon.plugins.validation.constraints.ObjectValidator]
    at griffon.util.GriffonClassUtils.requireState(GriffonClassUtils.java:279)
    at org.codehaus.griffon.runtime.validation.constraints.ValidatorConstraint.setParameter(ValidatorConstraint.java:73)
    at griffon.plugins.validation.constraints.ConstrainedProperty.applyConstraint(ConstrainedProperty.java:900)
    at org.codehaus.griffon.runtime.validation.constraints.GroovyAwareConstrainedPropertyAssembler$ConstrainedPropertyBuilder.addConstraint(GroovyAwareConstrainedPropertyAssembler.java:167)
    at org.codehaus.griffon.runtime.validation.constraints.GroovyAwareConstrainedPropertyAssembler$ConstrainedPropertyBuilder.createNode(GroovyAwareConstrainedPropertyAssembler.java:155)
    at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:84)
    at org.codehaus.griffon.runtime.validation.constraints.GroovyAwareConstrainedPropertyAssembler$ConstrainedPropertyBuilder.doInvokeMethod(GroovyAwareConstrainedPropertyAssembler.java:92)
    at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
    at groovy.lang.MetaClassImpl.invokeMethodOnGroovyObject(MetaClassImpl.java:1277)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1109)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
    at au.edu.nsw.det.esbtoolsfx.validate.PermissionValidator$__clinit__closure1.doCall(PermissionValidator.groovy:20)
    at au.edu.nsw.det.esbtoolsfx.validate.PermissionValidator$__clinit__closure1.doCall(PermissionValidator.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1212)
    at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
    at groovy.lang.Closure.call(Closure.java:426)
    at groovy.lang.Closure.call(Closure.java:420)
    at org.codehaus.griffon.runtime.validation.constraints.GroovyAwareConstrainedPropertyAssembler.assemble(GroovyAwareConstrainedPropertyAssembler.java:75)
    at org.codehaus.griffon.runtime.validation.constraints.DefaultConstraintsEvaluator.evaluateConstraints(DefaultConstraintsEvaluator.java:105)
    at org.codehaus.griffon.runtime.validation.constraints.DefaultConstraintsEvaluator.evaluate(DefaultConstraintsEvaluator.java:64)
    at org.codehaus.griffon.runtime.validation.AbstractValidateable.initialize(AbstractValidateable.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.griffon.runtime.injection.MethodUtils$1.run(MethodUtils.java:79)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.codehaus.griffon.runtime.injection.MethodUtils.invokeAnnotatedMethod(MethodUtils.java:73)
    at org.codehaus.griffon.runtime.injection.GuiceInjectorFactory$2.afterInjection(GuiceInjectorFactory.java:89)
    at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:115)
    at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
    at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
    at org.codehaus.griffon.runtime.injection.GuiceInjectorFactory$3$4.onProvision(GuiceInjectorFactory.java:128)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
    at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
    at org.codehaus.griffon.runtime.injection.GuiceInjector.getInstance(GuiceInjector.java:147)
    at griffon.core.injection.Injector$getInstance.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
    at au.edu.nsw.det.esbtoolsfx.validate.ValidationManager.validate(ValidationManager.groovy:24)
    at au.edu.nsw.det.esbtoolsfx.validate.ValidationManager.validate(ValidationManager.groovy:22)
    at au.edu.nsw.det.esbtoolsfx.validate.ValidationManager$validate.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
    at au.edu.nsw.det.esbtoolsfx.RTPermissionController.clickOK(RTPermissionController.groovy:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at griffon.util.MethodUtils.invokeExactMethod(MethodUtils.java:388)
    at griffon.util.MethodUtils.invokeExactMethod(MethodUtils.java:339)
    at griffon.util.GriffonClassUtils.invokeExactInstanceMethod(GriffonClassUtils.java:3052)
    at org.codehaus.griffon.runtime.core.controller.AbstractActionManager.doInvokeAction(AbstractActionManager.java:338)
    at org.codehaus.griffon.runtime.core.controller.AbstractActionManager$1.run(AbstractActionManager.java:257)
    at org.codehaus.griffon.runtime.core.threading.AbstractUIThreadManager$1.run(AbstractUIThreadManager.java:95)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by shnplr** [comment]
Debugging ValidatorConstraint.setParameter(Object) show constraintParameter is a PermissionValidator$__clinit__closure1$_closure2@7080

**Comment by shnplr** [comment]
Hi,
Is it possible to reopen this issue?
